from mapnik import (Map, Image, Envelope, render, Rule, Color,
                    Style, PolygonSymbolizer, LineSymbolizer)

m = Map(800, 400)
image = Image(800, 400)
rule = Rule()
rule.symbols.append(PolygonSymbolizer(Color("#f2eff9")))
rule.symbols.append(LineSymbolizer(Color("black"), 0.1))
style = Style()
style.rules.append(rule)
m.append_style(rule)
layer = Layer('world')
layer.datasource = Shapefile(file='path/to/shapefile')
layer.styles.append('Base')
m.layers.append(layer)
m.zoom_to_box(layer.envelope())
render(m, image)
